import { metric } from "@sunreye/profile-sdk";

/** Generator input ports. */
export const generator = [
  metric("ac/generator/a/voltage", {
    label: "Gen port A Voltage",
    unit: "V",
    group: "generator",
    addr: 661,
    scale: 0.1,
    role: "generator.phase.voltage",
    index: 1,
    deadband: 1,
  }),
  metric("ac/generator/b/voltage", {
    label: "Gen port B Voltage",
    unit: "V",
    group: "generator",
    addr: 662,
    scale: 0.1,
    role: "generator.phase.voltage",
    index: 2,
    deadband: 1,
  }),
  metric("ac/generator/c/voltage", {
    label: "Gen port C Voltage",
    unit: "V",
    group: "generator",
    addr: 663,
    scale: 0.1,
    role: "generator.phase.voltage",
    index: 3,
    deadband: 1,
  }),
  metric("ac/generator/a/power", {
    label: "Gen port A Power",
    unit: "W",
    group: "generator",
    addr: 664,
    role: "generator.phase.power",
    index: 1,
    deadband: 20,
  }),
  metric("ac/generator/b/power", {
    label: "Gen port B Power",
    unit: "W",
    group: "generator",
    addr: 665,
    role: "generator.phase.power",
    index: 2,
    deadband: 20,
  }),
  metric("ac/generator/c/power", {
    label: "Gen port C Power",
    unit: "W",
    group: "generator",
    addr: 666,
    role: "generator.phase.power",
    index: 3,
    deadband: 20,
  }),
  metric("ac/generator/total_power", {
    label: "Total Power of Gen Ports",
    unit: "W",
    group: "generator",
    addr: 667,
    role: "generator.power",
    deadband: 20,
  }),
  metric("ac/generator/daily_energy", {
    label: "Daily Generator Production",
    unit: "kWh",
    group: "generator",
    addr: 536,
    scale: 0.1,
    role: "generator.energy.today",
  }),
  // Vendor doc v105.4: 537/538 total generator production (low/high word),
  // 539 daily run time, 512/513 lifetime run time (low/high word). Hour and
  // kWh counters, so no deadband — a threshold makes a counter lag.
  metric("ac/generator/total_energy", {
    label: "Total Generator Production",
    unit: "kWh",
    group: "generator",
    type: "U_DWORD",
    addr: [537, 538],
    scale: 0.1,
    role: "generator.energy.total",
  }),
  metric("ac/generator/daily_runtime", {
    label: "Generator Run Time Today",
    kind: "cumulative",
    unit: "h",
    group: "generator",
    addr: 539,
    scale: 0.1,
  }),
  metric("ac/generator/total_runtime", {
    label: "Total Generator Run Time",
    kind: "cumulative",
    unit: "h",
    group: "generator",
    type: "U_DWORD",
    addr: [512, 513],
    scale: 0.1,
  }),
];
