import { metric } from "@sunreye/profile-sdk";
import { GRID_FLOW } from "./conventions";

/** Grid side: per-phase voltage/current/power, CT clamps, import/export counters. */
export const grid = [
  metric("ac/total_power", {
    label: "Total Grid Power",
    unit: "W",
    group: "inverter",
    type: "S_WORD",
    addr: 625,
    role: "grid.power",
    flow: GRID_FLOW,
    deadband: 20,
  }),
  metric("ac/l1/voltage", {
    label: "Grid Voltage L1",
    unit: "V",
    group: "inverter",
    addr: 598,
    scale: 0.1,
    role: "grid.phase.voltage",
    index: 1,
    deadband: 1,
  }),
  metric("ac/l2/voltage", {
    label: "Grid Voltage L2",
    unit: "V",
    group: "inverter",
    addr: 599,
    scale: 0.1,
    role: "grid.phase.voltage",
    index: 2,
    deadband: 1,
  }),
  metric("ac/l3/voltage", {
    label: "Grid Voltage L3",
    unit: "V",
    group: "inverter",
    addr: 600,
    scale: 0.1,
    role: "grid.phase.voltage",
    index: 3,
    deadband: 1,
  }),
  metric("ac/l1/ct/internal", {
    label: "Internal CT L1 Power",
    unit: "W",
    group: "inverter",
    type: "S_WORD",
    addr: 604,
    role: "grid.phase.power",
    index: 1,
    flow: GRID_FLOW,
    deadband: 20,
  }),
  metric("ac/l2/ct/internal", {
    label: "Internal CT L2 Power",
    unit: "W",
    group: "inverter",
    type: "S_WORD",
    addr: 605,
    role: "grid.phase.power",
    index: 2,
    flow: GRID_FLOW,
    deadband: 20,
  }),
  metric("ac/l3/ct/internal", {
    label: "Internal CT L3 Power",
    unit: "W",
    group: "inverter",
    type: "S_WORD",
    addr: 606,
    role: "grid.phase.power",
    index: 3,
    flow: GRID_FLOW,
    deadband: 20,
  }),
  metric("ac/total_internal_power", {
    label: "Total Internal Power",
    unit: "W",
    group: "inverter",
    type: "S_WORD",
    addr: 607,
    kind: "measurement",
    deadband: 20,
  }),
  metric("ac/l1/ct/external", {
    label: "External CT L1 Power",
    unit: "W",
    group: "inverter",
    type: "S_WORD",
    addr: 616,
    kind: "measurement",
    deadband: 20,
  }),
  metric("ac/l2/ct/external", {
    label: "External CT L2 Power",
    unit: "W",
    group: "inverter",
    type: "S_WORD",
    addr: 617,
    kind: "measurement",
    deadband: 20,
  }),
  metric("ac/l3/ct/external", {
    label: "External CT L3 Power",
    unit: "W",
    group: "inverter",
    type: "S_WORD",
    addr: 618,
    kind: "measurement",
    deadband: 20,
  }),
  metric("ac/daily_energy_bought", {
    label: "Daily Energy Bought",
    unit: "kWh",
    group: "inverter",
    addr: 520,
    scale: 0.1,
    role: "grid.energy.imported.today",
  }),
  metric("ac/total_energy_bought", {
    label: "Total Energy Bought",
    unit: "kWh",
    group: "inverter",
    type: "U_DWORD",
    addr: [522, 523],
    scale: 0.1,
    role: "grid.energy.imported.total",
  }),
  metric("ac/daily_energy_sold", {
    label: "Daily Energy Sold",
    unit: "kWh",
    group: "inverter",
    addr: 521,
    scale: 0.1,
    role: "grid.energy.exported.today",
  }),
  metric("ac/total_energy_sold", {
    label: "Total Energy Sold",
    unit: "kWh",
    group: "inverter",
    type: "U_DWORD",
    addr: [524, 525],
    scale: 0.1,
    role: "grid.energy.exported.total",
  }),
  metric("ac/l1/current", {
    label: "Current L1",
    unit: "A",
    group: "inverter",
    type: "S_WORD",
    addr: 630,
    scale: 0.01,
    role: "grid.phase.current",
    index: 1,
    flow: GRID_FLOW,
    deadband: 0.2,
  }),
  metric("ac/l2/current", {
    label: "Current L2",
    unit: "A",
    group: "inverter",
    type: "S_WORD",
    addr: 631,
    scale: 0.01,
    role: "grid.phase.current",
    index: 2,
    flow: GRID_FLOW,
    deadband: 0.2,
  }),
  metric("ac/l3/current", {
    label: "Current L3",
    unit: "A",
    group: "inverter",
    type: "S_WORD",
    addr: 632,
    scale: 0.01,
    role: "grid.phase.current",
    index: 3,
    flow: GRID_FLOW,
    deadband: 0.2,
  }),
  metric("ac/l1/power", {
    label: "Inverter L1 Power",
    unit: "W",
    group: "inverter",
    type: "S_WORD",
    addr: 633,
    kind: "measurement",
    deadband: 20,
  }),
  metric("ac/l2/power", {
    label: "Inverter L2 Power",
    unit: "W",
    group: "inverter",
    type: "S_WORD",
    addr: 634,
    kind: "measurement",
    deadband: 20,
  }),
  metric("ac/l3/power", {
    label: "Inverter L3 Power",
    unit: "W",
    group: "inverter",
    type: "S_WORD",
    addr: 635,
    kind: "measurement",
    deadband: 20,
  }),
  // Vendor "+1000" temperature encoding: register = °C×10 + 1000, so decode as
  // raw×0.1 − 100. Without the offset these read ~100 °C high (25 → 125).
  // Per-phase CT currents, the current-side companions to the CT powers above:
  // 610-612 internal CT (电网侧内侧电流, doc v105.4), 613-615 external CT
  // (电网外置-电流 — the doc's English "Out-of-grid" is a mistranslation; the
  // Chinese and the 616-618 pairing both say external CT). Signed, 0.01 A.
  metric("ac/l1/ct/internal_current", {
    label: "Grid Internal CT Current L1",
    kind: "measurement",
    unit: "A",
    group: "inverter",
    type: "S_WORD",
    addr: 610,
    scale: 0.01,
    flow: GRID_FLOW,
    deadband: 0.2,
  }),
  metric("ac/l1/ct/external_current", {
    label: "Grid External CT Current L1",
    kind: "measurement",
    unit: "A",
    group: "inverter",
    type: "S_WORD",
    addr: 613,
    scale: 0.01,
    flow: GRID_FLOW,
    deadband: 0.2,
  }),
  metric("ac/l2/ct/internal_current", {
    label: "Grid Internal CT Current L2",
    kind: "measurement",
    unit: "A",
    group: "inverter",
    type: "S_WORD",
    addr: 611,
    scale: 0.01,
    flow: GRID_FLOW,
    deadband: 0.2,
  }),
  metric("ac/l2/ct/external_current", {
    label: "Grid External CT Current L2",
    kind: "measurement",
    unit: "A",
    group: "inverter",
    type: "S_WORD",
    addr: 614,
    scale: 0.01,
    flow: GRID_FLOW,
    deadband: 0.2,
  }),
  metric("ac/l3/ct/internal_current", {
    label: "Grid Internal CT Current L3",
    kind: "measurement",
    unit: "A",
    group: "inverter",
    type: "S_WORD",
    addr: 612,
    scale: 0.01,
    flow: GRID_FLOW,
    deadband: 0.2,
  }),
  metric("ac/l3/ct/external_current", {
    label: "Grid External CT Current L3",
    kind: "measurement",
    unit: "A",
    group: "inverter",
    type: "S_WORD",
    addr: 615,
    scale: 0.01,
    flow: GRID_FLOW,
    deadband: 0.2,
  }),
];
