import { metric } from "@sunreye/profile-sdk";

/** Backup / UPS load output. */
export const load = [
  metric("ac/ups/total_power", {
    label: "Total Load Power",
    unit: "W",
    group: "load",
    addr: 653,
    role: "load.power",
    deadband: 20,
  }),
  metric("ac/ups/l1/power", {
    label: "Load L1 Power",
    unit: "W",
    group: "load",
    addr: 650,
    role: "load.phase.power",
    index: 1,
    deadband: 20,
  }),
  metric("ac/ups/l2/power", {
    label: "Load L2 Power",
    unit: "W",
    group: "load",
    addr: 651,
    role: "load.phase.power",
    index: 2,
    deadband: 20,
  }),
  metric("ac/ups/l3/power", {
    label: "Load L3 Power",
    unit: "W",
    group: "load",
    addr: 652,
    role: "load.phase.power",
    index: 3,
    deadband: 20,
  }),
  metric("ac/ups/l1/voltage", {
    label: "Load Voltage L1",
    unit: "V",
    group: "load",
    addr: 644,
    scale: 0.1,
    role: "load.phase.voltage",
    index: 1,
    deadband: 1,
  }),
  metric("ac/ups/l2/voltage", {
    label: "Load Voltage L2",
    unit: "V",
    group: "load",
    addr: 645,
    scale: 0.1,
    role: "load.phase.voltage",
    index: 2,
    deadband: 1,
  }),
  metric("ac/ups/l3/voltage", {
    label: "Load Voltage L3",
    unit: "V",
    group: "load",
    addr: 646,
    scale: 0.1,
    role: "load.phase.voltage",
    index: 3,
    deadband: 1,
  }),
  metric("ac/ups/daily_energy", {
    label: "Daily Load Consumption",
    unit: "kWh",
    group: "load",
    addr: 526,
    scale: 0.1,
    role: "load.energy.today",
  }),
  metric("ac/ups/total_energy", {
    label: "Total Load Consumption",
    unit: "kWh",
    group: "load",
    type: "U_DWORD",
    addr: [527, 528],
    scale: 0.1,
    role: "load.energy.total",
  }),
];
