import { metric } from "@sunreye/profile-sdk";

/** PV strings (per-MPPT power / voltage / current) and production counters. */
export const solar = [
  metric("dc/pv1/power", {
    label: "PV1 Power",
    unit: "W",
    group: "inverter",
    addr: 672,
    role: "pv.string.power",
    index: 1,
    deadband: 20,
  }),
  metric("dc/pv2/power", {
    label: "PV2 Power",
    unit: "W",
    group: "inverter",
    addr: 673,
    role: "pv.string.power",
    index: 2,
    deadband: 20,
  }),
  metric("dc/pv1/voltage", {
    label: "PV1 Voltage",
    unit: "V",
    group: "inverter",
    addr: 676,
    scale: 0.1,
    role: "pv.string.voltage",
    index: 1,
    deadband: 1,
  }),
  metric("dc/pv2/voltage", {
    label: "PV2 Voltage",
    unit: "V",
    group: "inverter",
    addr: 678,
    scale: 0.1,
    role: "pv.string.voltage",
    index: 2,
    deadband: 1,
  }),
  metric("dc/pv1/current", {
    label: "PV1 Current",
    unit: "A",
    group: "inverter",
    addr: 677,
    scale: 0.1,
    role: "pv.string.current",
    index: 1,
    deadband: 0.2,
  }),
  metric("dc/pv2/current", {
    label: "PV2 Current",
    unit: "A",
    group: "inverter",
    addr: 679,
    scale: 0.1,
    role: "pv.string.current",
    index: 2,
    deadband: 0.2,
  }),
  // PV3/PV4 (doc v105.4: 674/675 power, 680-683 voltage/current). The 14K+ SKUs
  // have four PV string inputs across their two MPP trackers; the 3-12K SKUs
  // have two, and drop these in their model overlays. The datasheet counts
  // strings per tracker as "2+1", so trust the hardware over that row.
  metric("dc/pv3/power", {
    label: "PV3 Power",
    unit: "W",
    group: "inverter",
    addr: 674,
    role: "pv.string.power",
    index: 3,
    deadband: 20,
  }),
  metric("dc/pv3/voltage", {
    label: "PV3 Voltage",
    unit: "V",
    group: "inverter",
    addr: 680,
    scale: 0.1,
    role: "pv.string.voltage",
    index: 3,
    deadband: 1,
  }),
  metric("dc/pv3/current", {
    label: "PV3 Current",
    unit: "A",
    group: "inverter",
    addr: 681,
    scale: 0.1,
    role: "pv.string.current",
    index: 3,
    deadband: 0.2,
  }),
  metric("dc/pv4/power", {
    label: "PV4 Power",
    unit: "W",
    group: "inverter",
    addr: 675,
    role: "pv.string.power",
    index: 4,
    deadband: 20,
  }),
  metric("dc/pv4/voltage", {
    label: "PV4 Voltage",
    unit: "V",
    group: "inverter",
    addr: 682,
    scale: 0.1,
    role: "pv.string.voltage",
    index: 4,
    deadband: 1,
  }),
  metric("dc/pv4/current", {
    label: "PV4 Current",
    unit: "A",
    group: "inverter",
    addr: 683,
    scale: 0.1,
    role: "pv.string.current",
    index: 4,
    deadband: 0.2,
  }),
  metric("day_energy", {
    label: "Daily Production",
    unit: "kWh",
    group: "inverter",
    addr: 529,
    scale: 0.1,
    role: "production.today",
  }),
  metric("total_energy", {
    label: "Total Production",
    unit: "kWh",
    group: "inverter",
    type: "U_DWORD",
    addr: [534, 535],
    scale: 0.1,
    role: "production.total",
  }),
];
